python/Workmate - Django/workmate/exhibition_app/urls.py
from django.urls import path
from . import views

app_name = 'exhibition_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('add-owner/', views.add_owner, name='add_owner'),
    path('add-cat/', views.add_cat, name='add_cat'),
    path('edit-cat/<int:pk>/', views.edit_cat, name='edit_cat'),
    path('delete-cat/<int:pk>/', views.delete_cat, name='delete_cat'),
    path('list-cats/', views.list_cats, name='list_cats'),
    path('add-rating/', views.add_rating, name='add_rating'),
    path('ratings/', views.ratings, name='ratings'),
    path('cats/', views.all_cats, name='all_cats'),
    path('cats/<str:breed>/', views.all_cats, name='cats_by_breeds'),
    path('cat/<int:pk>/', views.get_cat_info, name='cat_info'),
    path('breeds/', views.kitten_breeds, name='kitten_breeds'),
]

python/Workmate - Django/workmate/workmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# Swagger документация
schema_view = get_schema_view(
    openapi.Info(
        title="Выставка кошек API",
        default_version='v1',
        description="API для управления выставкой кошек с JWT авторизацией",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@exhibition.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exhibition_app.urls')),
    path('api/v1/', include('exhibition_app.api_urls')),
    
    # Swagger документация
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/Workmate - Django/workmate/exhibition_app/models.py
from django.db import models

# Create your models here.


class KittenOwner(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    patronymic = models.CharField(max_length=50)

    def __str__(self):
        return f'name: {self.name} surname: {self.surname}, patronymic: {self.patronymic}'


class Cat(models.Model):
    colors = models.CharField(max_length=50)
    mounts = models.IntegerField()
    kitten_breed = models.CharField(max_length=50)
    description = models.TextField()
    photo = models.ImageField(upload_to='cats/')
    kitten_owner = models.ForeignKey(KittenOwner, on_delete=models.CASCADE)

    def __str__(self):
        return f'color: {self.colors}, mounts: {self.mounts}, kitten breed: {self.kitten_breed}, desc: {self.description}, kitten owner: {self.kitten_owner}'


class Images(models.Model):
    cat_photo = models.ForeignKey(Cat, on_delete=models.CASCADE)
    author = models.ForeignKey(KittenOwner, on_delete=models.CASCADE)

    def __str__(self):
        return  f'Photo of {self.cat_photo} by {self.author}'


class Rating(models.Model):
    RATING_CHOICES = [
        (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')
    ]
    
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
    author = models.ForeignKey(KittenOwner, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    
    class Meta:
        unique_together = ('cat', 'author') 
    
    def __str__(self):
        return f'Rating {self.rating} for {self.cat} by {self.author}'

python/Workmate - Django/workmate/exhibition_app/views.py
from django.http import JsonResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.db import models

from .models import KittenOwner, Cat, Rating, Images

# Create your views here.


def home(request):
    cats_count = Cat.objects.count()
    owners_count = KittenOwner.objects.count()
    breeds_count = Cat.objects.values('kitten_breed').distinct().count()

    context = {
        'cats_count': cats_count,
        'owners_count': owners_count,
        'breeds_count': breeds_count,
    }
    return render(request, 'exhibition_app/home.html', context)


def add_owner(request):
    context = {}
    if request.method == 'POST':
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        patronymic = request.POST.get('patronymic')

        if name and surname and patronymic:
            owner = KittenOwner.objects.create(
                name=name,
                surname=surname,
                patronymic=patronymic
            )
            context = {
                'message': f'Владелец {surname} {name} {patronymic} успешно добавлен!',
                'error': False
            }
        else:
            context = {
                'message': 'Пожалуйста, заполните все поля',
                'error': True
            }

    return render(request, 'exhibition_app/add_owner.html', context)


def add_cat(request):
    owners = KittenOwner.objects.all()
    context = {'owners': owners}

    if request.method == 'POST':
        colors = request.POST.get('colors')
        mounts = request.POST.get('mounts')
        kitten_breed = request.POST.get('kitten_breed')
        description = request.POST.get('description')
        photo = request.FILES.get('photo')
        kitten_owner_id = request.POST.get('kitten_owner')

        if all([colors, mounts, kitten_breed, description, photo, kitten_owner_id]):
            try:
                kitten_owner = KittenOwner.objects.get(id=kitten_owner_id)
                cat = Cat.objects.create(
                    colors=colors,
                    mounts=int(mounts),
                    kitten_breed=kitten_breed,
                    description=description,
                    photo=photo,
                    kitten_owner=kitten_owner
                )
                context = {
                    'message': f'Кошка породы {kitten_breed} успешно добавлена!',
                    'error': False,
                    'owners': owners
                }
            except KittenOwner.DoesNotExist:
                context = {
                    'message': 'Выбранный владелец не найден',
                    'error': True,
                    'owners': owners
                }
        else:
            context = {
                'message': 'Пожалуйста, заполните все поля',
                'error': True,
                'owners': owners
            }

    return render(request, 'exhibition_app/add_cat.html', context)


def edit_cat(request, pk):
    cat = get_object_or_404(Cat, pk=pk)
    owners = KittenOwner.objects.all()

    if request.method == 'POST':
        colors = request.POST.get('colors')
        mounts = request.POST.get('mounts')
        kitten_breed = request.POST.get('kitten_breed')
        description = request.POST.get('description')
        photo = request.FILES.get('photo')
        kitten_owner_id = request.POST.get('kitten_owner')

        if all([colors, mounts, kitten_breed, description, kitten_owner_id]):
            try:
                kitten_owner = KittenOwner.objects.get(id=kitten_owner_id)
                cat.colors = colors
                cat.mounts = int(mounts)
                cat.kitten_breed = kitten_breed
                cat.description = description
                cat.kitten_owner = kitten_owner

                if photo:
                    cat.photo = photo

                cat.save()
                context = {
                    'message': f'Кошка породы {kitten_breed} успешно обновлена!',
                    'error': False,
                    'cat': cat,
                    'owners': owners
                }
            except KittenOwner.DoesNotExist:
                context = {
                    'message': 'Выбранный владелец не найден',
                    'error': True,
                    'cat': cat,
                    'owners': owners
                }
        else:
            context = {
                'message': 'Пожалуйста, заполните все обязательные поля',
                'error': True,
                'cat': cat,
                'owners': owners
            }
    else:
        context = {
            'cat': cat,
            'owners': owners
        }

    return render(request, 'exhibition_app/edit_cat.html', context)


def delete_cat(request, pk):
    if request.method == 'POST':
        cat = get_object_or_404(Cat, pk=pk)
        cat.delete()
        return redirect('exhibition_app:list_cats')
    return redirect('exhibition_app:list_cats')


def list_cats(request):
    cats = Cat.objects.select_related('kitten_owner').all()
    
    # Добавляем информацию о рейтингах для каждой кошки
    for cat in cats:
        ratings = Rating.objects.filter(cat=cat)
        cat.ratings_count = ratings.count()
        if cat.ratings_count > 0:
            cat.average_rating = ratings.aggregate(avg=models.Avg('rating'))['avg']
        else:
            cat.average_rating = None
    
    context = {'cats': cats}
    return render(request, 'exhibition_app/list_cats.html', context)

def add_rating(request):
    cats = Cat.objects.select_related('kitten_owner').all()
    owners = KittenOwner.objects.all()
    
    # Если передан параметр cat, предвыбираем кошку
    selected_cat = request.GET.get('cat')
    
    if request.method == 'POST':
        cat_id = request.POST.get('cat')
        author_id = request.POST.get('author')
        rating_value = request.POST.get('rating')
        
        if all([cat_id, author_id, rating_value]):
            try:
                cat = Cat.objects.get(id=cat_id)
                author = KittenOwner.objects.get(id=author_id)
                
                # Проверяем, не оценивал ли уже этот пользователь эту кошку
                existing_rating = Rating.objects.filter(cat=cat, author=author).first()
                
                if existing_rating:
                    # Обновляем существующую оценку
                    existing_rating.rating = int(rating_value)
                    existing_rating.save()
                    message = f'Ваша оценка для {cat.kitten_breed} обновлена на {rating_value} звезд!'
                else:
                    # Создаем новую оценку
                    Rating.objects.create(
                        cat=cat,
                        author=author,
                        rating=int(rating_value)
                    )
                    message = f'Спасибо! Вы оценили {cat.kitten_breed} на {rating_value} звезд!'
                
                context = {
                    'message': message,
                    'error': False,
                    'cats': cats,
                    'owners': owners
                }
            except (Cat.DoesNotExist, KittenOwner.DoesNotExist):
                context = {
                    'message': 'Ошибка: кошка или владелец не найдены',
                    'error': True,
                    'cats': cats,
                    'owners': owners
                }
        else:
            context = {
                'message': 'Пожалуйста, заполните все поля',
                'error': True,
                'cats': cats,
                'owners': owners
            }
    else:
        context = {
            'cats': cats,
            'owners': owners,
            'selected_cat': selected_cat
        }
    
    return render(request, 'exhibition_app/add_rating.html', context)


def ratings(request):
    # Получаем кошек с рейтингами, отсортированных по среднему рейтингу
    cats_with_ratings = []
    
    for cat in Cat.objects.select_related('kitten_owner').all():
        ratings = Rating.objects.filter(cat=cat)
        cat.ratings_count = ratings.count()
        
        if cat.ratings_count > 0:
            cat.average_rating = ratings.aggregate(avg=models.Avg('rating'))['avg']
            # Получаем последние 3 оценки
            cat.recent_ratings = ratings.select_related('author').order_by('-id')[:3]
            cats_with_ratings.append(cat)
    
    # Сортируем по среднему рейтингу (по убыванию)
    cats_with_ratings.sort(key=lambda x: x.average_rating, reverse=True)
    
    context = {'cats_with_ratings': cats_with_ratings}
    return render(request, 'exhibition_app/ratings.html', context)


def all_cats(request, breed=None):
    if breed is None:
        breed = request.GET.get('breed')

    if breed is None:
        cats = Cat.objects.all()
        response_data = {'intro': 'All cats'}
    else:
        if not Cat.objects.filter(kitten_breed=breed).exists():
            return JsonResponse({
                'error': f'Cat with breed = {breed} not found'
            }, status=400)
        cats = Cat.objects.filter(kitten_breed=breed).values(
            'id',
            'color',
            'mounts',
            'kitten_breeds',
            'description',
            'photo',
            'kitten_owner'
        )
        response_data = {'intro': f'Cats of breed: {breed}', 'breed': breed}

    response_data['total_count'] = cats.count()
    response_data['cats'] = list(cats.values('id', 'colors', 'mounts', 'kitten_breed', 'description', 'photo', 'kitten_owner'
                                             ))
    return JsonResponse(response_data, encoder=DjangoJSONEncoder)


def kitten_breeds(request):
    breeds = Cat.objects.values_list('kitten_breed', flat=True).distinct()
    response_data = {
        'intro': 'All kitten breeds',

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/add_cat.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Добавить кошку{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Добавить кошку</h1>
    
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="colors">Окрас:</label>
            <input type="text" id="colors" name="colors" required>
        </div>
        
        <div class="form-group">
            <label for="mounts">Возраст (месяцев):</label>
            <input type="number" id="mounts" name="mounts" min="0" required>
        </div>
        
        <div class="form-group">
            <label for="kitten_breed">Порода:</label>
            <input type="text" id="kitten_breed" name="kitten_breed" required>
        </div>
        
        <div class="form-group">
            <label for="description">Описание:</label>
            <textarea id="description" name="description" rows="4" required></textarea>
        </div>
        
        <div class="form-group">
            <label for="photo">Фото:</label>
            <input type="file" id="photo" name="photo" accept="image/*" required>
        </div>
        
        <div class="form-group">
            <label for="kitten_owner">Владелец:</label>
            <select id="kitten_owner" name="kitten_owner" required>
                <option value="">Выберите владельца</option>
                {% for owner in owners %}
                <option value="{{ owner.id }}">{{ owner.surname }} {{ owner.name }} {{ owner.patronymic }}</option>
                {% endfor %}
            </select>
        </div>
        
        <button type="submit" class="btn btn-primary">Добавить кошку</button>
    </form>
    
    {% if message %}
    <div class="message {% if error %}error{% else %}success{% endif %}">
        {{ message }}
    </div>
    {% endif %}
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/add_owner.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Добавить владельца{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Добавить владельца кошки</h1>
    
    <form method="post" class="form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Имя:</label>
            <input type="text" id="name" name="name" required>
        </div>
        
        <div class="form-group">
            <label for="surname">Фамилия:</label>
            <input type="text" id="surname" name="surname" required>
        </div>
        
        <div class="form-group">
            <label for="patronymic">Отчество:</label>
            <input type="text" id="patronymic" name="patronymic" required>
        </div>
        
        <button type="submit" class="btn btn-primary">Добавить владельца</button>
    </form>
    
    {% if message %}
    <div class="message {% if error %}error{% else %}success{% endif %}">
        {{ message }}
    </div>
    {% endif %}
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/add_rating.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Оценить котенка{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Оценить котенка</h1>
    
    <form method="post" class="form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="cat">Выберите котенка:</label>
            <select id="cat" name="cat" required>
                <option value="">Выберите котенка</option>
                {% for cat in cats %}
                <option value="{{ cat.id }}" {% if selected_cat == cat.id|stringformat:"s" %}selected{% endif %}>
                    {{ cat.kitten_breed }} - {{ cat.colors }} ({{ cat.kitten_owner.surname }} {{ cat.kitten_owner.name }})
                </option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="author">Ваше имя:</label>
            <select id="author" name="author" required>
                <option value="">Выберите ваше имя</option>
                {% for owner in owners %}
                <option value="{{ owner.id }}">
                    {{ owner.surname }} {{ owner.name }} {{ owner.patronymic }}
                </option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="rating">Оценка:</label>
            <div class="rating-stars">
                <input type="radio" id="star5" name="rating" value="5" required>
                <label for="star5">★</label>
                <input type="radio" id="star4" name="rating" value="4">
                <label for="star4">★</label>
                <input type="radio" id="star3" name="rating" value="3">
                <label for="star3">★</label>
                <input type="radio" id="star2" name="rating" value="2">
                <label for="star2">★</label>
                <input type="radio" id="star1" name="rating" value="1">
                <label for="star1">★</label>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Отправить оценку</button>
    </form>
    
    {% if message %}
    <div class="message {% if error %}error{% else %}success{% endif %}">
        {{ message }}
    </div>
    {% endif %}
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Выставка кошек{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'exhibition_app/css/style.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'exhibition_app:home' %}">Главная</a></li>
                <li><a href="{% url 'exhibition_app:add_cat' %}">Добавить кошку</a></li>
                <li><a href="{% url 'exhibition_app:add_owner' %}">Добавить владельца</a></li>
                <li><a href="{% url 'exhibition_app:list_cats' %}">Список кошек</a></li>
                <li><a href="{% url 'exhibition_app:add_rating' %}">Оценить котенка</a></li>
                <li><a href="{% url 'exhibition_app:ratings' %}">Рейтинги</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Выставка кошек</p>
    </footer>
</body>
</html> 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/edit_cat.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Редактировать кошку{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Редактировать кошку</h1>
    
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="colors">Окрас:</label>
            <input type="text" id="colors" name="colors" value="{{ cat.colors }}" required>
        </div>
        
        <div class="form-group">
            <label for="mounts">Возраст (месяцев):</label>
            <input type="number" id="mounts" name="mounts" value="{{ cat.mounts }}" min="0" required>
        </div>
        
        <div class="form-group">
            <label for="kitten_breed">Порода:</label>
            <input type="text" id="kitten_breed" name="kitten_breed" value="{{ cat.kitten_breed }}" required>
        </div>
        
        <div class="form-group">
            <label for="description">Описание:</label>
            <textarea id="description" name="description" rows="4" required>{{ cat.description }}</textarea>
        </div>
        
        <div class="form-group">
            <label for="photo">Фото:</label>
            <input type="file" id="photo" name="photo" accept="image/*">
            {% if cat.photo %}
            <p class="current-photo">Текущее фото: {{ cat.photo.name }}</p>
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="kitten_owner">Владелец:</label>
            <select id="kitten_owner" name="kitten_owner" required>
                {% for owner in owners %}
                <option value="{{ owner.id }}" {% if owner.id == cat.kitten_owner.id %}selected{% endif %}>
                    {{ owner.surname }} {{ owner.name }} {{ owner.patronymic }}
                </option>
                {% endfor %}
            </select>
        </div>
        
        <div class="button-group">
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            <a href="{% url 'exhibition_app:list_cats' %}" class="btn btn-secondary">Отмена</a>
        </div>
    </form>
    
    {% if message %}
    <div class="message {% if error %}error{% else %}success{% endif %}">
        {{ message }}
    </div>
    {% endif %}
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/home.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Главная - Выставка кошек{% endblock %}

{% block content %}
<div class="home-container">
    <div class="hero">
        <h1>Добро пожаловать на выставку кошек!</h1>
        <p>Здесь вы можете управлять информацией о кошках и их владельцах</p>
    </div>
    
    <div class="stats">
        <div class="stat-card">
            <h3>{{ cats_count }}</h3>
            <p>Кошек в базе</p>
        </div>
        <div class="stat-card">
            <h3>{{ owners_count }}</h3>
            <p>Владельцев</p>
        </div>
        <div class="stat-card">
            <h3>{{ breeds_count }}</h3>
            <p>Пород</p>
        </div>
    </div>
    
    <div class="quick-actions">
        <h2>Быстрые действия</h2>
        <div class="action-buttons">
            <a href="{% url 'exhibition_app:add_cat' %}" class="btn btn-primary">Добавить кошку</a>
            <a href="{% url 'exhibition_app:add_owner' %}" class="btn btn-secondary">Добавить владельца</a>
            <a href="{% url 'exhibition_app:list_cats' %}" class="btn btn-info">Посмотреть всех кошек</a>
        </div>
    </div>
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/list_cats.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Список кошек{% endblock %}

{% block content %}
<div class="container">
    <h1>Список кошек</h1>
    
    <div class="actions">
        <a href="{% url 'exhibition_app:add_cat' %}" class="btn btn-primary">Добавить кошку</a>
    </div>
    
    {% if cats %}
    <div class="cats-grid">
        {% for cat in cats %}
        <div class="cat-card">
            {% if cat.photo %}
            <img src="{{ cat.photo.url }}" alt="Фото кошки" class="cat-photo">
            {% else %}
            <div class="no-photo">Нет фото</div>
            {% endif %}
            
            <div class="cat-info">
                <h3>{{ cat.kitten_breed }}</h3>
                <p><strong>Окрас:</strong> {{ cat.colors }}</p>
                <p><strong>Возраст:</strong> {{ cat.mounts }} месяцев</p>
                <p><strong>Владелец:</strong> {{ cat.kitten_owner.surname }} {{ cat.kitten_owner.name }}</p>
                <p><strong>Описание:</strong> {{ cat.description|truncatewords:10 }}</p>
                
                <!-- Рейтинг -->
                <div class="cat-rating">
                    <p><strong>Рейтинг:</strong></p>
                    <div class="rating-display">
                        {% if cat.average_rating %}
                            <span class="stars">
                                {% for i in "12345" %}
                                    {% if forloop.counter <= cat.average_rating %}
                                        <span class="star filled">★</span>
                                    {% else %}
                                        <span class="star">☆</span>
                                    {% endif %}
                                {% endfor %}
                            </span>
                            <span class="rating-text">{{ cat.average_rating|floatformat:1 }}/5 ({{ cat.ratings_count }} оценок)</span>
                        {% else %}
                            <span class="no-rating">Нет оценок</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            
            <div class="cat-actions">
                <a href="{% url 'exhibition_app:edit_cat' cat.id %}" class="btn btn-secondary">Редактировать</a>
                <a href="{% url 'exhibition_app:add_rating' %}?cat={{ cat.id }}" class="btn btn-info">Оценить</a>
                <form method="post" action="{% url 'exhibition_app:delete_cat' cat.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите удалить эту кошку?')">
                        Удалить
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="no-cats">
        <p>Кошки не найдены. <a href="{% url 'exhibition_app:add_cat' %}">Добавить первую кошку</a></p>
    </div>
    {% endif %}
</div>
{% endblock %} 

python/Workmate - Django/workmate/exhibition_app/templates/exhibition_app/ratings.html
{% extends 'exhibition_app/base.html' %}

{% block title %}Рейтинги котят{% endblock %}

{% block content %}
<div class="container">
    <h1>Рейтинги котят</h1>
    
    <div class="actions">
        <a href="{% url 'exhibition_app:add_rating' %}" class="btn btn-primary">Добавить оценку</a>
    </div>
    
    {% if cats_with_ratings %}
    <div class="ratings-grid">
        {% for cat in cats_with_ratings %}
        <div class="rating-card">
            {% if cat.photo %}
            <img src="{{ cat.photo.url }}" alt="Фото кошки" class="cat-photo">
            {% else %}
            <div class="no-photo">Нет фото</div>
            {% endif %}
            
            <div class="rating-info">
                <h3>{{ cat.kitten_breed }}</h3>
                <p><strong>Окрас:</strong> {{ cat.colors }}</p>
                <p><strong>Владелец:</strong> {{ cat.kitten_owner.surname }} {{ cat.kitten_owner.name }}</p>
                
                <div class="rating-summary">
                    <div class="rating-stars-display">
                        {% for i in "12345" %}
                            {% if forloop.counter <= cat.average_rating %}
                                <span class="star filled">★</span>
                            {% else %}
                                <span class="star">☆</span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="rating-details">
                        <p class="rating-score">{{ cat.average_rating|floatformat:1 }}/5</p>
                        <p class="rating-count">{{ cat.ratings_count }} оценок</p>
                    </div>
                </div>
                
                {% if cat.recent_ratings %}
                <div class="recent-ratings">
                    <h4>Последние оценки:</h4>
                    {% for rating in cat.recent_ratings %}
                    <div class="rating-item">
                        <span class="rating-author">{{ rating.author.surname }} {{ rating.author.name }}</span>
                        <span class="rating-value">
                            {% for i in "12345" %}
                                {% if forloop.counter <= rating.rating %}
                                    <span class="star filled">★</span>
                                {% else %}
                                    <span class="star">☆</span>
                                {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="no-ratings">
        <p>Пока нет оценок. <a href="{% url 'exhibition_app:add_rating' %}">Добавить первую оценку</a></p>
    </div>
    {% endif %}
</div>
{% endblock %} 